spring:
  application:
    name: gateway

server:
  port: 8080
  
zuul:
  prefix: /api
  routes:
    account-service:
      path: /account/**
      
zuul:
  routes:
    discovery:
      path: /discovery-transaction/**
      url: http://localhost:8761
