server:
  port: 8080
  
spring:
  application:
    name: transaction-api-proxy
  
zuul:
  routes:
    account-service:
      path: /api/account/**
      url: account-service
      
zuul:
  routes:
    discovery:
      path: /discovery-transaction/**
      url: http://localhost:8761
